<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
	<TargetFrameworks>net9.0-windows;net10.0-windows;net9.0;net10.0</TargetFrameworks>
	<ApplicationIcon>Resources\as.ico</ApplicationIcon>
	<Copyright>Copyright © Escartem 2024-2026; Copyright © Razmoth 2022-2024; Copyright © Perfare 2018-2022</Copyright>
	<RuntimeIdentifier Condition="'$(TargetFramework)' == 'net9.0-windows' Or '$(TargetFramework)' == 'net10.0-windows'">win-x64</RuntimeIdentifier>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.CommandLine" Version="2.0.9" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\AnimeStudio.Utility\AnimeStudio.Utility.csproj" />
    <ProjectReference Include="..\AnimeStudio\AnimeStudio.csproj" />
  </ItemGroup>

  <ItemGroup>
		<ContentWithTargetPath Include="..\LICENSE">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>LICENSE</TargetPath>
		</ContentWithTargetPath>
	</ItemGroup>

  <ItemGroup>
    <Compile Update="Settings.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

	<Target Name="RemoveSkiaSharpPdb" AfterTargets="ResolveAssemblyReferences;Build">
		<ItemGroup>
			<NativePdbFiles Include="$(OutDir)*.pdb" />
			<NativePdbFiles Include="$(PublishDir)*.pdb" Condition="'$(PublishDir)' != ''" />
		</ItemGroup>
		<Delete Files="@(NativePdbFiles)" />
	</Target>

</Project>
